# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/eliasn/406a0a4f-2264-42b3-ad67-11f22a9bd2461/school/computer_graphics/project/P1/ImageEditing-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/eliasn/406a0a4f-2264-42b3-ad67-11f22a9bd2461/school/computer_graphics/project/P1/ImageEditing-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/eliasn/406a0a4f-2264-42b3-ad67-11f22a9bd2461/school/computer_graphics/project/P1/ImageEditing-master/CMakeFiles /media/eliasn/406a0a4f-2264-42b3-ad67-11f22a9bd2461/school/computer_graphics/project/P1/ImageEditing-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/eliasn/406a0a4f-2264-42b3-ad67-11f22a9bd2461/school/computer_graphics/project/P1/ImageEditing-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImageEditing

# Build rule for target.
ImageEditing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImageEditing
.PHONY : ImageEditing

# fast build rule for target.
ImageEditing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/build
.PHONY : ImageEditing/fast

#=============================================================================
# Target rules for targets named libtarga

# Build rule for target.
libtarga: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libtarga
.PHONY : libtarga

# fast build rule for target.
libtarga/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtarga.dir/build.make CMakeFiles/libtarga.dir/build
.PHONY : libtarga/fast

src/ImageWidget.o: src/ImageWidget.cpp.o
.PHONY : src/ImageWidget.o

# target to build an object file
src/ImageWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/ImageWidget.cpp.o
.PHONY : src/ImageWidget.cpp.o

src/ImageWidget.i: src/ImageWidget.cpp.i
.PHONY : src/ImageWidget.i

# target to preprocess a source file
src/ImageWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/ImageWidget.cpp.i
.PHONY : src/ImageWidget.cpp.i

src/ImageWidget.s: src/ImageWidget.cpp.s
.PHONY : src/ImageWidget.s

# target to generate assembly for a file
src/ImageWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/ImageWidget.cpp.s
.PHONY : src/ImageWidget.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/ScriptHandler.o: src/ScriptHandler.cpp.o
.PHONY : src/ScriptHandler.o

# target to build an object file
src/ScriptHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/ScriptHandler.cpp.o
.PHONY : src/ScriptHandler.cpp.o

src/ScriptHandler.i: src/ScriptHandler.cpp.i
.PHONY : src/ScriptHandler.i

# target to preprocess a source file
src/ScriptHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/ScriptHandler.cpp.i
.PHONY : src/ScriptHandler.cpp.i

src/ScriptHandler.s: src/ScriptHandler.cpp.s
.PHONY : src/ScriptHandler.s

# target to generate assembly for a file
src/ScriptHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/ScriptHandler.cpp.s
.PHONY : src/ScriptHandler.cpp.s

src/TargaImage.o: src/TargaImage.cpp.o
.PHONY : src/TargaImage.o

# target to build an object file
src/TargaImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/TargaImage.cpp.o
.PHONY : src/TargaImage.cpp.o

src/TargaImage.i: src/TargaImage.cpp.i
.PHONY : src/TargaImage.i

# target to preprocess a source file
src/TargaImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/TargaImage.cpp.i
.PHONY : src/TargaImage.cpp.i

src/TargaImage.s: src/TargaImage.cpp.s
.PHONY : src/TargaImage.s

# target to generate assembly for a file
src/TargaImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageEditing.dir/build.make CMakeFiles/ImageEditing.dir/src/TargaImage.cpp.s
.PHONY : src/TargaImage.cpp.s

src/libtarga.o: src/libtarga.c.o
.PHONY : src/libtarga.o

# target to build an object file
src/libtarga.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtarga.dir/build.make CMakeFiles/libtarga.dir/src/libtarga.c.o
.PHONY : src/libtarga.c.o

src/libtarga.i: src/libtarga.c.i
.PHONY : src/libtarga.i

# target to preprocess a source file
src/libtarga.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtarga.dir/build.make CMakeFiles/libtarga.dir/src/libtarga.c.i
.PHONY : src/libtarga.c.i

src/libtarga.s: src/libtarga.c.s
.PHONY : src/libtarga.s

# target to generate assembly for a file
src/libtarga.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libtarga.dir/build.make CMakeFiles/libtarga.dir/src/libtarga.c.s
.PHONY : src/libtarga.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ImageEditing"
	@echo "... libtarga"
	@echo "... src/ImageWidget.o"
	@echo "... src/ImageWidget.i"
	@echo "... src/ImageWidget.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/ScriptHandler.o"
	@echo "... src/ScriptHandler.i"
	@echo "... src/ScriptHandler.s"
	@echo "... src/TargaImage.o"
	@echo "... src/TargaImage.i"
	@echo "... src/TargaImage.s"
	@echo "... src/libtarga.o"
	@echo "... src/libtarga.i"
	@echo "... src/libtarga.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

